-- MySQL Script generated by MySQL Workbench
-- Mon Mar 11 17:34:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gereciamento_psicologa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gereciamento_psicologa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gereciamento_psicologa` DEFAULT CHARACTER SET utf8 ;
USE `gereciamento_psicologa` ;

-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Senha` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Funcionarios` (
  `idFuncionarios` INT NOT NULL,
  `NomeCompleto` VARCHAR(60) NOT NULL,
  `Bairro` VARCHAR(60) NOT NULL,
  `Cidade` VARCHAR(60) NOT NULL,
  `Nacionalidade` VARCHAR(60) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `NumeroRegistro` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  `Idade` INT NOT NULL,
  PRIMARY KEY (`idFuncionarios`),
  UNIQUE INDEX `idFuncionarios_UNIQUE` (`idFuncionarios` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Perfil_Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Idade` INT NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `RG` VARCHAR(45) ,
  `Cidade` VARCHAR(60) NOT NULL,
  `Nacionalidade` VARCHAR(20) NOT NULL,
  `Bairro` VARCHAR(60) NOT NULL,Nx
  `Nome_Mae` VARCHAR(50) NOT NULL,
  `Nome_Pai` VARCHAR(50) NOT NULL,
  `Sexo` VARCHAR(15) NOT NULL,
  `Data_emissao` DATE NOT NULL,
  `Data_expiracao` DATE NOT NULL,
  `idUsuario` INT ,
  `ativo_inativo` TINYINT NOT NULL,
  
  `Funcionarios_idFuncionarios` INT ,
  `Celular` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idPaciente`),
  INDEX `fk_Perfil_Paciente_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Perfil_Paciente_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_Paciente_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `gereciamento_psicologa`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_Paciente_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `gereciamento_psicologa`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
select * from Paciente;

-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Protuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Protuario` (
  `idProtuario` INT NOT NULL AUTO_INCREMENT,
  `NomePsicologa` VARCHAR(60) NOT NULL,
  `NomePaciente` VARCHAR(60) NOT NULL,
  `Sessao_numero` INT NOT NULL,
  `Sugestao_ativ_semana_anterior` VARCHAR(300) NOT NULL,
  `Descricao_sessao` VARCHAR(500) NOT NULL,
  `Objetivo_sessao` VARCHAR(300) NOT NULL,
  `Tecnicas_instrumentos` VARCHAR(300) NOT NULL,
  `Disfuncoes_cognitivas` VARCHAR(300) NOT NULL,
  `Tarefa_casa` VARCHAR(500) NOT NULL,
  `Resultados_esperados_X_obitidos` VARCHAR(300) NOT NULL,
  `ResumoSessao` VARCHAR(1500) NOT NULL,
  `idPaciente` INT NOT NULL,
  `Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idProtuario`),
  INDEX `fk_Protuario_Perfil_Paciente1_idx` (`idPaciente` ASC) VISIBLE,
  INDEX `fk_Protuario_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Protuario_Perfil_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `gereciamento_psicologa`.`Perfil_Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Protuario_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `gereciamento_psicologa`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Recibo` (
  `idRecibo` INT NOT NULL AUTO_INCREMENT,
  `NomePsicologa` VARCHAR(60) NOT NULL,
  `CPF_psicologa` VARCHAR(11) NOT NULL,
  `CPF_cliente` VARCHAR(11) NOT NULL,
  `NomeCliente` VARCHAR(60) NOT NULL,
  `ValorRecibo` DECIMAL(6,2) NOT NULL,
  `DATA_Recibo` DATE NOT NULL,
  `idPaciente` INT NOT NULL,
  `Funcionarios_idFuncionarios` INT NOT NULL,
  `Nome_do_Beneficiario` VARCHAR(45) NULL,
  PRIMARY KEY (`idRecibo`),
  INDEX `fk_Recibo_Perfil_Paciente1_idx` (`idPaciente` ASC) VISIBLE,
  INDEX `fk_Recibo_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Recibo_Perfil_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `gereciamento_psicologa`.`Perfil_Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibo_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `gereciamento_psicologa`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Diagrama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Diagrama` (
  `idDiagrama` INT NOT NULL AUTO_INCREMENT,
  `NomePaciente` VARCHAR(60) NOT NULL,
  `DATA_diagrama` DATE NOT NULL,
  `Dados_revelantes_infancia` VARCHAR(450) NOT NULL,
  `CrencaCentral` VARCHAR(450) NOT NULL,
  `EstrategiasCompesatorias` VARCHAR(450) NOT NULL,
  `Dificuldades` VARCHAR(450) NOT NULL,
  `1pensamento_automatico` VARCHAR(450) NOT NULL,
  `2pensamento_automatico` VARCHAR(450) NOT NULL,
  `1emocao` VARCHAR(450) NOT NULL,
  `2emocao` VARCHAR(450) NOT NULL,
  `1comportamento` VARCHAR(450) NOT NULL,
  `2comportamento` VARCHAR(450) NOT NULL,
  `idPaciente` INT NOT NULL,
  `Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idDiagrama`),
  INDEX `fk_Diagrama_Perfil_Paciente1_idx` (`idPaciente` ASC) VISIBLE,
  INDEX `fk_Diagrama_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Diagrama_Perfil_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `gereciamento_psicologa`.`Perfil_Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagrama_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `gereciamento_psicologa`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Anamnese_Principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Anamnese_Principal` (
  `idAnamnese` INT NOT NULL AUTO_INCREMENT,
  `idPaciente` INT NOT NULL,
  `Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idAnamnese`),
  INDEX `fk_Anamnese_Principal_Perfil_Paciente1_idx` (`idPaciente` ASC) VISIBLE,
  INDEX `fk_Anamnese_Principal_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Anamnese_Principal_Perfil_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `gereciamento_psicologa`.`Perfil_Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anamnese_Principal_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `gereciamento_psicologa`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Dados_identificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Dados_identificacao` (
  `idDados_identificacao` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(60) NOT NULL,
  `Data_nascimento` DATE NOT NULL,
  `Idade` INT NOT NULL,
  `Profissao` VARCHAR(100) NOT NULL,
  `Curso_ou_trabalho` VARCHAR(100) NOT NULL,
  `Periodo_ou_empresa` VARCHAR(100) NOT NULL,
  `Estado_Civil` VARCHAR(20) NOT NULL,
  `Filhos` INT NULL,
  `Contato` VARCHAR(20) NOT NULL,
  `Contato_emergencia` VARCHAR(20) NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idDados_identificacao`),
  INDEX `fk_Dados_identificacao_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Dados_identificacao_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Dados_Familiares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Dados_Familiares` (
  `idDados_Familiares` INT NOT NULL AUTO_INCREMENT,
  `NomePai` VARCHAR(60) NOT NULL,
  `Idade_Pai` INT NOT NULL,
  `Profissao_Pai` VARCHAR(100) NOT NULL,
  `Grau_instrucao_Pai` VARCHAR(100) NULL,
  `Nome_Mae` VARCHAR(60) NOT NULL,
  `idade_Mae` INT NOT NULL,
  `Profissao_Mae` VARCHAR(100) NOT NULL,
  `Grau_instrucao_Mae` VARCHAR(100) NULL,
  `Estado_Civil` VARCHAR(20) NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idDados_Familiares`),
  INDEX `fk_Dados_Familiares_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Dados_Familiares_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Queixa_principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Queixa_principal` (
  `idQueixa_principal` INT NOT NULL AUTO_INCREMENT,
  `Motivo_busca_terapia` VARCHAR(400) NOT NULL,
  `Inicio_queixa` DATE NOT NULL,
  `Evolucao_queixa` VARCHAR(400) NOT NULL,
  `Mudancas_ocorridas` VARCHAR(250) NOT NULL,
  `Sintomas` VARCHAR(300) NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idQueixa_principal`),
  INDEX `fk_Queixa_principal_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Queixa_principal_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Historia_Clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Historia_Clinica` (
  `idHistoria_Clinica` INT NOT NULL AUTO_INCREMENT,
  `Doenca_cronica` VARCHAR(145) NOT NULL,
  `Uso_medicamentos` VARCHAR(100) NOT NULL,
  `Casos_Internacao` VARCHAR(340) NOT NULL,
  `Sintomas_fisicos_e/ou_psicologicos` VARCHAR(300) NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idHistoria_Clinica`),
  INDEX `fk_Historia_Clinica_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Historia_Clinica_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Tabela_Interesses_Gerais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Tabela_Interesses_Gerais` (
  `idInteressesGerais` INT NOT NULL AUTO_INCREMENT,
  `Interesses` VARCHAR(500) NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idInteressesGerais`),
  INDEX `fk_Tabela_Interesses_Gerais_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Tabela_Interesses_Gerais_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Vida_escolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Vida_escolar` (
  `idVidaEscolar` INT NOT NULL AUTO_INCREMENT,
  `Relacao_colegas` VARCHAR(200) NULL,
  `Relacao_professores` VARCHAR(200) NULL,
  `Notas_escola` VARCHAR(70) NULL,
  `Materias_melhor_desempenho` VARCHAR(100) NULL,
  `Numeros_amigos` INT NULL,
  `idAnamnese` INT NULL,
  PRIMARY KEY (`idVidaEscolar`),
  INDEX `fk_Vida_escolar_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Vida_escolar_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Vida_Familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Vida_Familiar` (
  `idVidaFamiliar` INT NOT NULL AUTO_INCREMENT,
  `Mora_com_pais` VARCHAR(50) NOT NULL,
  `Relacao_pais` VARCHAR(400) NOT NULL,
  `Relacao_irmaos` VARCHAR(400) NOT NULL,
  `Conversa_com_pais_ou_conjuque` VARCHAR(500) NOT NULL,
  `Tempo_de_frequencia` INT NOT NULL,
  `Familia_religiosa` VARCHAR(60) NOT NULL,
  `Infancia` VARCHAR(1000) NOT NULL,
  `7_a_12_anos` VARCHAR(700) NOT NULL,
  `12_a_18_anos` VARCHAR(700) NOT NULL,
  `Tratamento_pais` VARCHAR(500) NOT NULL,
  `Estudo` VARCHAR(400) NOT NULL,
  `Amigos` VARCHAR(400) NOT NULL,
  `Bullying` VARCHAR(400) NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idVidaFamiliar`),
  INDEX `fk_Vida_Familiar_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Vida_Familiar_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`AutoConceito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`AutoConceito` (
  `idAutoConceito` INT NOT NULL AUTO_INCREMENT,
  `Intrepretacao_como_marido_ou_esposa` VARCHAR(500) NOT NULL,
  `Interpretacao_como_filho` VARCHAR(500) NOT NULL,
  `Visao_como_serHumano` VARCHAR(500) NOT NULL,
  `Aspecto_melhorar` VARCHAR(400) NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idAutoConceito`),
  INDEX `fk_AutoConceito_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_AutoConceito_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Vida_atual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Vida_atual` (
  `idVida_atual` INT NOT NULL AUTO_INCREMENT,
  `Relacao_familia` VARCHAR(500) NOT NULL,
  `Estudo` VARCHAR(500) NOT NULL,
  `Formacao` VARCHAR(150) NOT NULL,
  `Gosta_Trabalho` VARCHAR(300) NOT NULL,
  `Vida_social` VARCHAR(300) NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idVida_atual`),
  INDEX `fk_Vida_atual_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Vida_atual_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Vida_religiosa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Vida_religiosa` (
  `idVida_religiosa` INT NOT NULL AUTO_INCREMENT,
  `Religiao` VARCHAR(150) NULL,
  `Frequenta_igreja` VARCHAR(15) NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`idVida_religiosa`),
  INDEX `fk_Vida_religiosa_Anamnese_Principal1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Vida_religiosa_Anamnese_Principal1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `gereciamento_psicologa`.`Anamnese_Principal` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Ficha_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Ficha_cadastro` (
  `idFicha_cadastro` INT NOT NULL AUTO_INCREMENT,
  `Arquivo` LONGBLOB NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idFicha_cadastro`),
  INDEX `fk_Ficha_cadastro_Perfil_Paciente_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_Ficha_cadastro_Perfil_Paciente`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `gereciamento_psicologa`.`Perfil_Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Convenio` (
  `idConvenio` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `Perfil_Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idConvenio`),
  UNIQUE INDEX `idConvenio_UNIQUE` (`idConvenio` ASC) VISIBLE,
  INDEX `fk_Convenio_Perfil_Paciente1_idx` (`Perfil_Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_Convenio_Perfil_Paciente1`
    FOREIGN KEY (`Perfil_Paciente_idPaciente`)
    REFERENCES `gereciamento_psicologa`.`Perfil_Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Atendimento` (
  `idAtendimento` INT NOT NULL AUTO_INCREMENT,
  `horarioInicio` DATETIME NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `MetodoDePagamento` VARCHAR(35) NOT NULL,
  `Perfil_Paciente_idPaciente` INT ,
  `Funcionarios_idFuncionarios` INT ,
  `Descricao` VARCHAR(85) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Protuario_idProtuario` INT,
  `Desconto` DOUBLE NULL,
  `Convenio_idConvenio` INT ,
  `Convenio` VARCHAR(45) NULL,
  `HorarioFim` DATETIME NOT NULL,
  PRIMARY KEY (`idAtendimento`),
  UNIQUE INDEX `idAgendamento_UNIQUE` (`idAtendimento` ASC) VISIBLE,
  INDEX `fk_Agendamento_Perfil_Paciente1_idx` (`Perfil_Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Atendimento_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  INDEX `fk_Atendimento_Protuario1_idx` (`Protuario_idProtuario` ASC) VISIBLE,
  INDEX `fk_Atendimento_Convenio1_idx` (`Convenio_idConvenio` ASC) VISIBLE,
  CONSTRAINT `fk_Agendamento_Perfil_Paciente1`
    FOREIGN KEY (`Perfil_Paciente_idPaciente`)
    REFERENCES `gereciamento_psicologa`.`Perfil_Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimento_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `gereciamento_psicologa`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimento_Protuario1`
    FOREIGN KEY (`Protuario_idProtuario`)
    REFERENCES `gereciamento_psicologa`.`Protuario` (`idProtuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimento_Convenio1`
    FOREIGN KEY (`Convenio_idConvenio`)
    REFERENCES `gereciamento_psicologa`.`Convenio` (`idConvenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from atendimento;
-- -----------------------------------------------------
-- Table `gereciamento_psicologa`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gereciamento_psicologa`.`Agenda` (
  `idAgenda` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `DataInicio` DATETIME NOT NULL,
  `DataFim` DATETIME NOT NULL,
  `Atendimento_idAtendimento` INT NOT NULL,
  `Perfil_Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idAgenda`),
  UNIQUE INDEX `idAgenda_UNIQUE` (`idAgenda` ASC) VISIBLE,
  INDEX `fk_Agenda_Atendimento1_idx` (`Atendimento_idAtendimento` ASC) VISIBLE,
  INDEX `fk_Agenda_Perfil_Paciente1_idx` (`Perfil_Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_Agenda_Atendimento1`
    FOREIGN KEY (`Atendimento_idAtendimento`)
    REFERENCES `gereciamento_psicologa`.`Atendimento` (`idAtendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agenda_Perfil_Paciente1`
    FOREIGN KEY (`Perfil_Paciente_idPaciente`)
    REFERENCES `gereciamento_psicologa`.`Perfil_Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
